/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\apartment.glb 
Author: Mikita_Hubanau (https://sketchfab.com/Mikita_Hubanau)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-micro-apartments-fd8011e2af0e43288f5445600197ea77
Title: Cyberpunk Micro-Apartments
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Apartment(props) {
  const { nodes, materials } = useGLTF('models/apartment.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.UV_TEST} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['gran.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.glass} />
      </group>
    </group>
  )
}

useGLTF.preload('models/apartment.glb')
